# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Input tow varibel xand y and find X in to the power of Y
x = int(input('Enter the value of X:'))
y = int(input('Enter the value of Y:'))

# X in to the power of Y = Z
z = pow(x,y)
print('Z=',z)

